import type { Metadata } from 'next';
import { LegalPage, LegalSection } from '@/components/LegalPage';

export const metadata: Metadata = { title: 'Terms of Service · Knewit' };
export default function TermsPage() {
  return <LegalPage title="Terms of Service" effectiveDate="September 21, 2026">
    <LegalSection title="1. Introduction"><p>These Terms of Service (“Terms”) govern your access to and use of Knewit, including the Knewit mobile application, website, APIs, and related services (collectively, the “Services”).</p><p>Knewit is a social prediction market application that may provide prediction market information and functionality through third-party services, including Polymarket, and authentication and wallet functionality through Privy.</p><p>By using Knewit, you acknowledge that you have read, understood, and agree to these Terms and our Privacy Policy. If you do not agree, you must not use the Services. Third-party services operate under their own terms, policies, eligibility requirements, and restrictions.</p></LegalSection>
    <LegalSection title="2. Eligibility"><p>You may use Knewit only if legally permitted in your jurisdiction. You represent that you have legal capacity, satisfy applicable minimum-age requirements, are not prohibited by law or sanctions, and comply with third-party eligibility requirements.</p><p>You must not use VPNs, proxies, location spoofing, or other mechanisms to circumvent geographic, regulatory, or eligibility restrictions. Feature availability does not necessarily mean you are legally eligible to use an underlying third-party service.</p></LegalSection>
    <LegalSection title="3. Changes to These Terms"><p>We may modify these Terms to reflect changes to the Services, integrations, legal requirements, or business practices. Updated Terms become effective when published unless otherwise stated. Continued use after that date constitutes acceptance.</p></LegalSection>
    <LegalSection title="4. Changes to the Services"><p>Knewit may add, remove, modify, suspend, or discontinue features due to Polymarket or Privy changes, blockchain changes, regulatory requirements, security concerns, technical limitations, or other third-party changes. We do not guarantee that any feature, market, wallet functionality, or integration will remain available.</p></LegalSection>
    <LegalSection title="5. Accounts and Authentication"><p>Certain features require an account. Authentication may be provided through Privy, including email, social accounts, or other supported methods. You are responsible for your Knewit account, email, social accounts, device, wallet credentials, and other credentials, and for activity conducted through your account. Notify us if you reasonably believe your account is compromised.</p></LegalSection>
    <LegalSection title="6. Wallets and Privy"><p>Knewit may use Privy, a third-party wallet infrastructure provider, to create or connect cryptocurrency wallets. Your use of Privy is subject to its terms and policies.</p><p>Knewit does not intentionally request private keys or seed phrases through support channels. Never provide credentials or recovery phrases to Knewit personnel or users. Where wallets are non-custodial or user-controlled, you are responsible for access. Loss or compromise may cause permanent loss of assets, and Knewit cannot reverse blockchain transactions or recover assets where infrastructure does not permit it.</p></LegalSection>
    <LegalSection title="7. Polymarket Integration"><p>Knewit may integrate Polymarket APIs and infrastructure for market discovery, categories, descriptions, YES/NO outcomes, prices, probabilities, volume, liquidity, status, history, positions, and other public information.</p><p>Where supported, eligible users may initiate interactions with Polymarket infrastructure. Polymarket controls its own terms, privacy policy, geographic and age restrictions, wallet and KYC requirements, trading restrictions, market rules, and regulatory requirements. You are responsible for determining your eligibility.</p></LegalSection>
    <LegalSection title="8. Prediction Market Transactions"><p>Where available, Knewit acts as an interface to third-party prediction-market infrastructure. We do not guarantee execution, settlement, liquidity, execution price, market availability, outcome availability, continuous access, blockchain availability, or transaction reversal.</p><p>Blockchain transactions may be irreversible. Review transaction details before approving or signing.</p></LegalSection>
    <LegalSection title="9. Geographic and Regulatory Restrictions"><p>Prediction markets and cryptocurrency services are regulated differently by jurisdiction. Knewit may restrict functionality based on location, law, third-party restrictions, sanctions, Polymarket eligibility, wallet compatibility, or regulatory requirements. You must not bypass restrictions using VPNs, proxies, GPS spoofing, false information, or other circumvention methods.</p></LegalSection>
    <LegalSection title="10. Market Data"><p>Market data may originate from Polymarket or other third parties and may be delayed, unavailable, incomplete, incorrect, changed, or different from the underlying platform. Knewit does not guarantee accuracy, completeness, or real-time availability. Verify important information with the applicable underlying service before transacting.</p></LegalSection>
    <LegalSection title="11. Callouts and Social Features"><p>Knewit may allow users to create Callouts, share market opinions, select YES or NO positions, associate Callouts with markets, comment, reply, like, follow, share, and view profiles and activity. A Callout is user content and is not an endorsement, recommendation, or guarantee by Knewit.</p></LegalSection>
    <LegalSection title="12. User-Generated Content"><p>You retain applicable ownership rights in content you create. By publishing content, you grant Knewit a non-exclusive, worldwide, royalty-free license to host, store, reproduce, display, distribute, and process it as reasonably necessary to operate, improve, promote, and provide the Services. You represent that you have the rights to publish it. We may remove or restrict content violating these Terms, law, or community standards.</p></LegalSection>
    <LegalSection title="13. Community Conduct"><p>You must not publish unlawful, threatening, harassing, hateful, discriminatory, sexually exploitative, child-endangering, impersonating, fraudulent, deceptive, infringing, spam, malicious, asset-theft, phishing, scam, or wallet-draining content. We may remove content, restrict functionality, or suspend accounts.</p></LegalSection>
    <LegalSection title="14. Market Opinions and User Content"><p>User opinions belong to those users. Knewit does not verify or endorse every prediction, Callout, comment, analysis, profit claim, or strategy. Past performance does not guarantee future results. Independently evaluate information before making decisions.</p></LegalSection>
    <LegalSection title="15. Leaderboard and Performance Metrics"><p>Knewit may display PnL, prediction performance, trading activity, win rate, Callouts, engagement, and other metrics. Methodologies may change. Do not manipulate metrics through multiple accounts, wash trading, coordinated accounts, artificial transactions, fake engagement, selective transfers, or vulnerability exploitation. Knewit may recalculate, adjust, remove, or invalidate manipulated or erroneous metrics.</p></LegalSection>
    <LegalSection title="16. Fees and Third-Party Costs"><p>Knewit may display applicable transaction fees. Transactions may also involve blockchain, trading, protocol, market, wallet, and other third-party costs outside our control. Review transaction information before confirmation. Third-party fees may change independently.</p></LegalSection>
    <LegalSection title="17. Prediction Market Risks"><p>Prediction markets involve financial and market risk. Prices may change rapidly; you may lose some or all committed funds; liquidity may be limited; transactions may fail or be irreversible; infrastructure may be unavailable; smart contracts may contain vulnerabilities; resolution may differ from your interpretation; rules may change; and regulation may affect availability. Understand market rules before participating.</p></LegalSection>
    <LegalSection title="18. Market Resolution"><p>Markets may be resolved under rules established by Polymarket or another provider. Knewit does not independently determine Polymarket outcomes. Resolution may depend on rules, information sources, oracles, dispute mechanisms, and provider procedures. Review complete market rules before participating.</p></LegalSection>
    <LegalSection title="19. No Financial or Investment Advice"><p>Knewit content is for informational and social purposes. We do not provide financial, investment, tax, legal, securities, or trading advice. Prices, probabilities, Callouts, leaderboards, profiles, comments, and trends are not personalized advice. Knewit does not recommend any position or market. You are solely responsible for your decisions.</p></LegalSection>
    <LegalSection title="20. Prohibited Uses"><p>You may not violate law, bypass restrictions, access accounts without authorization, obtain credentials, conduct phishing or wallet-draining schemes, commit fraud, launder money, finance illegal activity, manipulate markets or leaderboards, inflate engagement, scrape without authorization, operate unauthorized bots, distribute malware, attack infrastructure, bypass security, reverse engineer where prohibited, abuse APIs, spam, impersonate, collect user data without authorization, or interfere with users.</p></LegalSection>
    <LegalSection title="21. Third-Party Services"><p>Knewit relies on third-party prediction markets, wallet infrastructure, authentication, blockchain networks, hosting, databases, analytics, market data, and other infrastructure. We cannot guarantee third-party security, uptime, accuracy, availability, or performance. Privy, Polymarket, blockchain, API, or other outages may affect Knewit.</p></LegalSection>
    <LegalSection title="22. Intellectual Property"><p>Except for user content and third-party materials, Knewit software, interfaces, branding, graphics, designs, and original content are owned by or licensed to Knewit. These Terms do not transfer ownership. You may not reproduce, distribute, sell, modify, or commercially exploit protected materials except as authorized or permitted by law.</p></LegalSection>
    <LegalSection title="23. Third-Party Trademarks"><p>Polymarket, Privy, and other third-party names, logos, trademarks, products, and services belong to their owners. References identify integrations and do not imply sponsorship, endorsement, partnership, or affiliation unless expressly stated.</p></LegalSection>
    <LegalSection title="24. Feedback"><p>By providing suggestions or feedback, you permit Knewit to use it to develop, improve, and operate the Services without compensation, subject to applicable law.</p></LegalSection>
    <LegalSection title="25. Suspension and Termination"><p>Knewit may restrict, suspend, or terminate an account for violating these Terms, fraud, security risks, manipulation, abuse, legal or sanctions requirements, third-party requirements, or activities threatening Knewit or users. Termination does not necessarily terminate or delete third-party wallets, accounts, or blockchain records.</p></LegalSection>
    <LegalSection title="26. Disclaimer of Warranties"><p>To the fullest extent permitted by law, Knewit is provided “as is” and “as available.” We do not guarantee availability, error-free operation, accurate market data, transaction execution, third-party availability, market access, or that the Services meet every user’s requirements. Nothing excludes rights that cannot lawfully be excluded.</p></LegalSection>
    <LegalSection title="27. Limitation of Liability"><p>To the fullest extent permitted by law, Knewit and its operators are not liable for indirect, incidental, special, consequential, or similar damages arising from the Services, including market movements, prediction outcomes, content, blockchain transactions, wallet or credential compromise, smart-contract failures, Polymarket or Privy outages, network failures, or incorrect or delayed data. Nothing limits liability where prohibited by law.</p></LegalSection>
    <LegalSection title="28. Taxes"><p>You are responsible for determining applicable taxes or reporting obligations for activity through third-party services. Knewit does not provide tax advice.</p></LegalSection>
    <LegalSection title="29. Privacy"><p>Your use of Knewit is also governed by the Knewit Privacy Policy, which explains how information may be collected, processed, stored, and shared.</p></LegalSection>
    <LegalSection title="30. Account Deletion"><p>Where supported, you may request deletion of your Knewit account. This may not delete public blockchain transactions, data retained by Polymarket or Privy, legally required records, or certain security, fraud-prevention, or compliance records. Third-party accounts and wallets must be managed under their providers’ policies.</p></LegalSection>
    <LegalSection title="31. Governing Law and Disputes"><p>These Terms are subject to applicable law. The final production version should identify the governing law, jurisdiction, dispute-resolution procedure, and legal entity responsible for Knewit based on the operator’s jurisdiction and corporate structure. Nothing limits mandatory consumer rights or legal protections.</p></LegalSection>
    <LegalSection title="32. Entire Agreement"><p>These Terms, the Knewit Privacy Policy, and additional terms presented for specific features constitute the agreement governing your use of Knewit. Third-party terms may also apply.</p></LegalSection>
    <LegalSection title="33. Severability"><p>If any provision is invalid or unenforceable, the remaining provisions remain in effect to the extent permitted by law.</p></LegalSection>
    <LegalSection title="34. Contact"><p>Questions, complaints, technical support requests, and other communications regarding these Terms should be directed to the official Knewit support contact listed in the application or on the Knewit website.</p><p>When you contact support about an account, market, or wallet action, provide the platform you used, the approximate time of the action, the market or feature involved, and any safe error code or transaction reference shown to you. Never provide a private key, recovery phrase, password, one-time code, or complete payment-card information.</p></LegalSection>
    <LegalSection title="35. Practical Use of Knewit"><p>Knewit helps users discover prediction markets, understand position information, and participate in public discussion. The Services are not a promise that every market, outcome, payment method, wallet action, or social feature will be available at every time or in every location.</p><p>Before using a feature, read the labels and confirmation information presented in Knewit. Before using an underlying third-party service, read the rules, eligibility requirements, fees, privacy terms, and any additional notices provided by that service. A feature appearing in the interface does not override a restriction imposed by law or by a third-party provider.</p><p>Use Knewit only for lawful personal purposes and only with an account, device, payment method, and wallet that you are authorized to use. Keep your account credentials private and review activity in your account regularly.</p></LegalSection>
    <LegalSection title="36. What to Check Before Market Activity"><p>Prediction markets can involve rapidly changing prices and outcomes. Before selecting an outcome or authorizing a transaction, read the complete market question, available outcomes, market rules, resolution source when available, displayed price, estimated amount, fees, wallet destination, and confirmation status.</p><p>A displayed price may be interpreted as a market-implied probability, but it is not a guarantee, a promise of return, or a recommendation from Knewit. Market activity, liquidity, order size, third-party availability, and timing can affect an order and its result. A submitted action is not complete until the relevant status is shown as confirmed.</p><p>If you do not understand the market, the transaction details, or the consequences of an action, do not proceed until you have obtained the information you need. Knewit does not provide personalized financial, legal, tax, or investment advice.</p></LegalSection>
    <LegalSection title="37. Wallet and Transfer Responsibilities"><p>Wallet addresses and blockchain transactions require careful review. An address may be correctly formatted without belonging to the intended recipient. You are responsible for reviewing the full recipient address, network, amount, and confirmation details before approving a withdrawal or other transfer.</p><p>Transactions can remain pending while they are being processed. Do not submit the same payment, order, or transfer again merely because a balance or status has not updated immediately. First review the status shown by Knewit and the connected provider, then use any transaction reference or support guidance available to you.</p><p>Where a blockchain transaction is final, it may be impossible to reverse, cancel, or recover. Knewit does not take custody of private keys or recovery phrases through support channels and cannot recover credentials or assets where the relevant infrastructure does not allow recovery.</p></LegalSection>
    <LegalSection title="38. Community Responsibilities"><p>Callouts, comments, replies, profiles, and other social features let users share views and discuss markets. You are responsible for the content you publish and for ensuring you have the right to publish it. Do not post personal information about another person without permission, misleading claims of certainty, impersonation, scams, harassment, or content that violates these Terms.</p><p>A Callout attached to a position gives readers context about the author’s view. It does not make the content verified, endorsed, or suitable for another person’s circumstances. Evaluate public content independently and make your own decisions.</p><p>Knewit may take action on content or accounts that create risk for users or the Services, including limiting visibility, removing content, restricting a feature, or suspending access as described in these Terms.</p></LegalSection>
  </LegalPage>;
}
