import type { Metadata } from 'next';
import { LegalPage, LegalSection } from '@/components/LegalPage';

export const metadata: Metadata = { title: 'Terms of Service · Knewit' };
export default function TermsPage() {
  return <LegalPage title="Terms of Service" effectiveDate="September 25, 2026">
    <LegalSection title="1. Introduction"><p>These Terms of Service (“Terms”) govern your access to and use of Knewit, including the Knewit mobile application, website, APIs, and related services (collectively, the “Services”).</p><p>Knewit is a social prediction market application. It provides sign-in and embedded wallets through Privy, and prediction markets, trading, portfolio data, and deposits and withdrawals through Polymarket, including Polymarket’s bridge.</p><p>By using Knewit, you agree to these Terms and acknowledge our Privacy Policy. If you do not agree, do not use the Services. Third-party services operate under their own terms, policies, eligibility requirements, and restrictions.</p></LegalSection>
    <LegalSection title="2. Eligibility"><p>You may use Knewit only if legally permitted in your jurisdiction. You represent that you have legal capacity, satisfy applicable minimum-age requirements, are not prohibited by law or sanctions, and comply with third-party eligibility requirements.</p><p>You must not use VPNs, proxies, location spoofing, or other mechanisms to circumvent geographic, regulatory, or eligibility restrictions. Feature availability does not necessarily mean you are legally eligible to use an underlying third-party service.</p></LegalSection>
    <LegalSection title="3. Changes to These Terms"><p>We may modify these Terms to reflect changes to the Services, integrations, legal requirements, or business practices. Updated Terms become effective when published unless otherwise stated. Continued use after that date constitutes acceptance.</p></LegalSection>
    <LegalSection title="4. Changes to the Services"><p>Knewit may add, remove, modify, suspend, or discontinue features due to Polymarket or Privy changes, blockchain changes, regulatory requirements, security concerns, technical limitations, or other third-party changes. We do not guarantee that any feature, market, wallet functionality, or integration will remain available.</p></LegalSection>
    <LegalSection title="5. Accounts and Authentication"><p>Certain features require an account. Authentication may be provided through Privy, including email, social accounts, or other supported methods. You are responsible for your Knewit account, email, social accounts, device, wallet credentials, and other credentials, and for activity conducted through your account. Notify us if you reasonably believe your account is compromised.</p></LegalSection>
    <LegalSection title="6. Wallets, Privy, and Signing Authorization"><p>When you sign in, Privy creates an embedded wallet for you, and Polymarket creates a Deposit Wallet (your trading wallet) controlled by that embedded wallet. Your trading balance (pUSD) and positions are held in the Deposit Wallet. Your use of Privy is subject to its terms and policies.</p><p>To carry out the trades, deposits, withdrawals, and redemptions you request, you authorize Knewit’s server as a signer on your embedded wallet through Privy. Knewit uses this authorization only for actions you start in the app. Knewit does not receive your private keys or recovery phrases and will never ask for them.</p><p>You are responsible for your sign-in methods and devices. Blockchain transactions cannot be reversed, and Knewit cannot recover assets where the underlying infrastructure does not allow it.</p></LegalSection>
    <LegalSection title="7. Polymarket Integration"><p>Knewit uses Polymarket’s APIs and infrastructure for market discovery, prices, order books, order placement, portfolio data, gasless wallet transactions, redemption, and the bridge used for deposits and withdrawals. Your balance, positions, and profit and loss are read from Polymarket.</p><p>Polymarket controls its own terms, privacy policy, geographic and age restrictions, market rules, fees, and regulatory requirements. You are responsible for determining that you are eligible to use Polymarket in your location.</p></LegalSection>
    <LegalSection title="8. Prediction Market Transactions"><p>Knewit is an interface to Polymarket. Buy and sell orders are placed as market orders (fill-and-kill): they fill against available liquidity immediately, and any unfilled part is cancelled. Selling closes everything you hold in that outcome. The estimate shown before you confirm is based on the current order book; the executed price and amount can differ.</p><p>An order is complete only when Knewit shows it as filled. When a market resolves in your favour, you can redeem the winning shares into trading balance. We do not guarantee execution, liquidity, price, market availability, or settlement, and blockchain transactions may be irreversible.</p></LegalSection>
    <LegalSection title="9. Geographic and Regulatory Restrictions"><p>Prediction markets and cryptocurrency services are regulated differently by jurisdiction. Knewit may restrict functionality based on location, law, third-party restrictions, sanctions, Polymarket eligibility, wallet compatibility, or regulatory requirements. You must not bypass restrictions using VPNs, proxies, GPS spoofing, false information, or other circumvention methods.</p></LegalSection>
    <LegalSection title="10. Market Data"><p>Market data may originate from Polymarket or other third parties and may be delayed, unavailable, incomplete, incorrect, changed, or different from the underlying platform. Knewit does not guarantee accuracy, completeness, or real-time availability. Verify important information with the applicable underlying service before transacting.</p></LegalSection>
    <LegalSection title="11. Callouts and Social Features"><p>Knewit may allow users to create Callouts, share market opinions, select YES or NO positions, associate Callouts with markets, comment, reply, like, follow, share, and view profiles and activity. A Callout is user content and is not an endorsement, recommendation, or guarantee by Knewit.</p></LegalSection>
    <LegalSection title="12. User-Generated Content"><p>You retain applicable ownership rights in content you create. By publishing content, you grant Knewit a non-exclusive, worldwide, royalty-free license to host, store, reproduce, display, distribute, and process it as reasonably necessary to operate, improve, promote, and provide the Services. You represent that you have the rights to publish it. We may remove or restrict content violating these Terms, law, or community standards.</p></LegalSection>
    <LegalSection title="13. Community Conduct"><p>You must not publish unlawful, threatening, harassing, hateful, discriminatory, sexually exploitative, child-endangering, impersonating, fraudulent, deceptive, infringing, spam, malicious, asset-theft, phishing, scam, or wallet-draining content. We may remove content, restrict functionality, or suspend accounts.</p></LegalSection>
    <LegalSection title="14. Market Opinions and User Content"><p>User opinions belong to those users. Knewit does not verify or endorse every prediction, Callout, comment, analysis, profit claim, or strategy. Past performance does not guarantee future results. Independently evaluate information before making decisions.</p></LegalSection>
    <LegalSection title="15. Leaderboard and Performance Metrics"><p>Knewit may display PnL, prediction performance, trading activity, win rate, Callouts, engagement, and other metrics. Methodologies may change. Do not manipulate metrics through multiple accounts, wash trading, coordinated accounts, artificial transactions, fake engagement, selective transfers, or vulnerability exploitation. Knewit may recalculate, adjust, remove, or invalidate manipulated or erroneous metrics.</p></LegalSection>
    <LegalSection title="16. Fees and Third-Party Costs"><p>Polymarket may charge platform fees on trades. Orders placed through Knewit carry Knewit’s Polymarket builder code, and Knewit may charge a builder fee on them within the limits Polymarket allows; any fee is included in the amount shown before you confirm a trade. Deposits and withdrawals through Polymarket’s bridge include bridge, swap, and network costs that are deducted from the amount transferred; the withdrawal screen shows the expected amount received and the route cost before you confirm. Third-party fees may change independently.</p></LegalSection>
    <LegalSection title="17. Prediction Market Risks"><p>Prediction markets involve financial and market risk. Prices may change rapidly; you may lose some or all committed funds; liquidity may be limited; transactions may fail or be irreversible; infrastructure may be unavailable; smart contracts may contain vulnerabilities; resolution may differ from your interpretation; rules may change; and regulation may affect availability. Understand market rules before participating.</p></LegalSection>
    <LegalSection title="18. Market Resolution"><p>Markets may be resolved under rules established by Polymarket or another provider. Knewit does not independently determine Polymarket outcomes. Resolution may depend on rules, information sources, oracles, dispute mechanisms, and provider procedures. Review complete market rules before participating.</p></LegalSection>
    <LegalSection title="19. No Financial or Investment Advice"><p>Knewit content is for informational and social purposes. We do not provide financial, investment, tax, legal, securities, or trading advice. Prices, probabilities, Callouts, leaderboards, profiles, comments, and trends are not personalized advice. Knewit does not recommend any position or market. You are solely responsible for your decisions.</p></LegalSection>
    <LegalSection title="20. Prohibited Uses"><p>You may not violate law, bypass restrictions, access accounts without authorization, obtain credentials, conduct phishing or wallet-draining schemes, commit fraud, launder money, finance illegal activity, manipulate markets or leaderboards, inflate engagement, scrape without authorization, operate unauthorized bots, distribute malware, attack infrastructure, bypass security, reverse engineer where prohibited, abuse APIs, spam, impersonate, collect user data without authorization, or interfere with users.</p></LegalSection>
    <LegalSection title="21. Third-Party Services"><p>Knewit relies on third-party prediction markets, wallet infrastructure, authentication, blockchain networks, hosting, databases, analytics, market data, and other infrastructure. We cannot guarantee third-party security, uptime, accuracy, availability, or performance. Privy, Polymarket, blockchain, API, or other outages may affect Knewit.</p></LegalSection>
    <LegalSection title="22. Intellectual Property"><p>Except for user content and third-party materials, Knewit software, interfaces, branding, graphics, designs, and original content are owned by or licensed to Knewit. These Terms do not transfer ownership. You may not reproduce, distribute, sell, modify, or commercially exploit protected materials except as authorized or permitted by law.</p></LegalSection>
    <LegalSection title="23. Third-Party Trademarks"><p>Polymarket, Privy, and other third-party names, logos, trademarks, products, and services belong to their owners. References identify integrations and do not imply sponsorship, endorsement, partnership, or affiliation unless expressly stated.</p></LegalSection>
    <LegalSection title="24. Feedback"><p>By providing suggestions or feedback, you permit Knewit to use it to develop, improve, and operate the Services without compensation, subject to applicable law.</p></LegalSection>
    <LegalSection title="25. Suspension and Termination"><p>Knewit may restrict, suspend, or terminate an account for violating these Terms, fraud, security risks, manipulation, abuse, legal or sanctions requirements, third-party requirements, or activities threatening Knewit or users. Termination does not necessarily terminate or delete third-party wallets, accounts, or blockchain records.</p></LegalSection>
    <LegalSection title="26. Disclaimer of Warranties"><p>To the fullest extent permitted by law, Knewit is provided “as is” and “as available.” We do not guarantee availability, error-free operation, accurate market data, transaction execution, third-party availability, market access, or that the Services meet every user’s requirements. Nothing excludes rights that cannot lawfully be excluded.</p></LegalSection>
    <LegalSection title="27. Limitation of Liability"><p>To the fullest extent permitted by law, Knewit and its operators are not liable for indirect, incidental, special, consequential, or similar damages arising from the Services, including market movements, prediction outcomes, content, blockchain transactions, wallet or credential compromise, smart-contract failures, Polymarket or Privy outages, network failures, or incorrect or delayed data. Nothing limits liability where prohibited by law.</p></LegalSection>
    <LegalSection title="28. Taxes"><p>You are responsible for determining applicable taxes or reporting obligations for activity through third-party services. Knewit does not provide tax advice.</p></LegalSection>
    <LegalSection title="29. Privacy"><p>Your use of Knewit is also governed by the Knewit Privacy Policy, which explains how information may be collected, processed, stored, and shared.</p></LegalSection>
    <LegalSection title="30. Account Deletion"><p>Where supported, you may request deletion of your Knewit account. This may not delete public blockchain transactions, data retained by Polymarket or Privy, legally required records, or certain security, fraud-prevention, or compliance records. Third-party accounts and wallets must be managed under their providers’ policies.</p></LegalSection>
    <LegalSection title="31. Governing Law and Disputes"><p>These Terms are subject to applicable law. The final production version should identify the governing law, jurisdiction, dispute-resolution procedure, and legal entity responsible for Knewit based on the operator’s jurisdiction and corporate structure. Nothing limits mandatory consumer rights or legal protections.</p></LegalSection>
    <LegalSection title="32. Entire Agreement"><p>These Terms, the Knewit Privacy Policy, and additional terms presented for specific features constitute the agreement governing your use of Knewit. Third-party terms may also apply.</p></LegalSection>
    <LegalSection title="33. Severability"><p>If any provision is invalid or unenforceable, the remaining provisions remain in effect to the extent permitted by law.</p></LegalSection>
    <LegalSection title="34. Contact"><p>Questions, complaints, technical support requests, and other communications regarding these Terms should be directed to the official Knewit support contact listed in the application or on the Knewit website.</p><p>When you contact support about an account, market, or wallet action, provide the platform you used, the approximate time of the action, the market or feature involved, and any safe error code or transaction reference shown to you. Never provide a private key, recovery phrase, password, one-time code, or complete payment-card information.</p></LegalSection>
    <LegalSection title="35. Practical Use of Knewit"><p>Knewit helps users discover prediction markets, understand position information, and participate in public discussion. The Services are not a promise that every market, outcome, payment method, wallet action, or social feature will be available at every time or in every location.</p><p>Before using a feature, read the labels and confirmation information presented in Knewit. Before using an underlying third-party service, read the rules, eligibility requirements, fees, privacy terms, and any additional notices provided by that service. A feature appearing in the interface does not override a restriction imposed by law or by a third-party provider.</p><p>Use Knewit only for lawful personal purposes and only with an account, device, payment method, and wallet that you are authorized to use. Keep your account credentials private and review activity in your account regularly.</p></LegalSection>
    <LegalSection title="36. What to Check Before Market Activity"><p>Prediction markets can involve rapidly changing prices and outcomes. Before selecting an outcome or authorizing a transaction, read the complete market question, available outcomes, market rules, resolution source when available, displayed price, estimated amount, fees, wallet destination, and confirmation status.</p><p>A displayed price may be interpreted as a market-implied probability, but it is not a guarantee, a promise of return, or a recommendation from Knewit. Market activity, liquidity, order size, third-party availability, and timing can affect an order and its result. A submitted action is not complete until the relevant status is shown as confirmed.</p><p>If you do not understand the market, the transaction details, or the consequences of an action, do not proceed until you have obtained the information you need. Knewit does not provide personalized financial, legal, tax, or investment advice.</p></LegalSection>
    <LegalSection title="37. Deposits, Withdrawals, and Transfer Responsibilities"><p><strong>Deposits.</strong> Deposits are processed by Polymarket’s bridge. Choose the token and chain in Knewit and send exactly that token, on that chain, to the deposit address shown. Each token and chain has a minimum, shown in the chain list. Deposits below the minimum, of a different token, or on a different chain may not be processed and may be lost. Deposits are credited as pUSD after the bridge completes; bridge costs are deducted from the amount.</p><p><strong>Withdrawals.</strong> Withdrawals send your trading balance through Polymarket’s bridge to the token, chain, and address you choose, subject to the minimum for that route. You are responsible for the recipient address and chain. An address can be correctly formatted without belonging to the intended recipient, and some exchanges do not accept every token or chain.</p><p><strong>Pending and failed transfers.</strong> Transfers can remain pending while they are processed. Do not repeat a deposit, order, or withdrawal just because a status has not updated yet. Polymarket’s bridge and its bridge provider operate independently of Knewit; recovery of funds sent incorrectly is not guaranteed. Knewit cannot reverse blockchain transactions.</p><p><strong>Card deposits.</strong> Where card deposits are offered, the purchase is made with a third-party provider such as MoonPay under its own terms, and the purchased funds are then sent to your Polymarket bridge deposit address.</p></LegalSection>
    <LegalSection title="38. Community Responsibilities"><p>Callouts, comments, replies, profiles, and other social features let users share views and discuss markets. You are responsible for the content you publish and for ensuring you have the right to publish it. Do not post personal information about another person without permission, misleading claims of certainty, impersonation, scams, harassment, or content that violates these Terms.</p><p>A Callout attached to a position gives readers context about the author’s view. It does not make the content verified, endorsed, or suitable for another person’s circumstances. Evaluate public content independently and make your own decisions.</p><p>Knewit may take action on content or accounts that create risk for users or the Services, including limiting visibility, removing content, restricting a feature, or suspending access as described in these Terms.</p></LegalSection>
  </LegalPage>;
}
