/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ApiCallsRouteImport } from './routes/api/calls'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiPositionsRouteImport } from './routes/api/positions'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsMarketIdRouteImport } from './routes/markets.$marketId'
import { Route as ApiCallsIdRouteImport } from './routes/api/calls.$id'
import { Route as ApiCommentsIdRouteImport } from './routes/api/comments.$id'
import { Route as ApiEventsIdRouteImport } from './routes/api/events.$id'
import { Route as ApiFeedFollowingRouteImport } from './routes/api/feed.following'
import { Route as ApiMarketsIdRouteImport } from './routes/api/markets.$id'
import { Route as ApiPositionsMarketIdRouteImport } from './routes/api/positions.$marketId'
import { Route as ApiTradingOrdersRouteImport } from './routes/api/trading.orders'
import { Route as ApiTradingSellRouteImport } from './routes/api/trading.sell'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as ApiUsersSuggestionsRouteImport } from './routes/api/users.suggestions'
import { Route as ApiWalletBalanceRouteImport } from './routes/api/wallet.balance'
import { Route as ApiWalletDepositWalletRouteImport } from './routes/api/wallet.deposit-wallet'
import { Route as ApiCallsIdCommentsRouteImport } from './routes/api/calls.$id.comments'
import { Route as ApiCallsIdLikeRouteImport } from './routes/api/calls.$id.like'
import { Route as ApiCommentsIdLikeRouteImport } from './routes/api/comments.$id.like'
import { Route as ApiCommentsIdRepliesRouteImport } from './routes/api/comments.$id.replies'
import { Route as ApiCommentsIdShareRouteImport } from './routes/api/comments.$id.share'
import { Route as ApiEventsIdActivityRouteImport } from './routes/api/events.$id.activity'
import { Route as ApiEventsIdHoldersRouteImport } from './routes/api/events.$id.holders'
import { Route as ApiMarketsIdActivityRouteImport } from './routes/api/markets.$id.activity'
import { Route as ApiMarketsIdHoldersRouteImport } from './routes/api/markets.$id.holders'
import { Route as ApiMarketsIdPriceHistoryRouteImport } from './routes/api/markets.$id.price-history'
import { Route as ApiMarketsIdTradeEstimateRouteImport } from './routes/api/markets.$id.trade-estimate'
import { Route as ApiUsersIdActivityRouteImport } from './routes/api/users.$id.activity'
import { Route as ApiUsersIdCallsRouteImport } from './routes/api/users.$id.calls'
import { Route as ApiUsersIdFollowRouteImport } from './routes/api/users.$id.follow'
import { Route as ApiUsersIdFollowersRouteImport } from './routes/api/users.$id.followers'
import { Route as ApiUsersIdFollowingRouteImport } from './routes/api/users.$id.following'
import { Route as ApiUsersIdRepliesRouteImport } from './routes/api/users.$id.replies'
import { Route as ApiUsersMeImagesRouteImport } from './routes/api/users.me.images'
import { Route as ApiWalletAllowanceRefreshRouteImport } from './routes/api/wallet.allowance.refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsRoute = ApiCallsRouteImport.update({
  id: '/api/calls',
  path: '/api/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPositionsRoute = ApiPositionsRouteImport.update({
  id: '/api/positions',
  path: '/api/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/$marketId',
  path: '/$marketId',
  getParentRoute: () => MarketsRoute,
} as any)
const ApiCallsIdRoute = ApiCallsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCallsRoute,
} as any)
const ApiCommentsIdRoute = ApiCommentsIdRouteImport.update({
  id: '/api/comments/$id',
  path: '/api/comments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIdRoute = ApiEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEventsRoute,
} as any)
const ApiFeedFollowingRoute = ApiFeedFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiMarketsIdRoute = ApiMarketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMarketsRoute,
} as any)
const ApiPositionsMarketIdRoute = ApiPositionsMarketIdRouteImport.update({
  id: '/$marketId',
  path: '/$marketId',
  getParentRoute: () => ApiPositionsRoute,
} as any)
const ApiTradingOrdersRoute = ApiTradingOrdersRouteImport.update({
  id: '/api/trading/orders',
  path: '/api/trading/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradingSellRoute = ApiTradingSellRouteImport.update({
  id: '/api/trading/sell',
  path: '/api/trading/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/api/users/$id',
  path: '/api/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersSuggestionsRoute = ApiUsersSuggestionsRouteImport.update({
  id: '/api/users/suggestions',
  path: '/api/users/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletBalanceRoute = ApiWalletBalanceRouteImport.update({
  id: '/api/wallet/balance',
  path: '/api/wallet/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletDepositWalletRoute = ApiWalletDepositWalletRouteImport.update({
  id: '/api/wallet/deposit-wallet',
  path: '/api/wallet/deposit-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsIdCommentsRoute = ApiCallsIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiCallsIdRoute,
} as any)
const ApiCallsIdLikeRoute = ApiCallsIdLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => ApiCallsIdRoute,
} as any)
const ApiCommentsIdLikeRoute = ApiCommentsIdLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => ApiCommentsIdRoute,
} as any)
const ApiCommentsIdRepliesRoute = ApiCommentsIdRepliesRouteImport.update({
  id: '/replies',
  path: '/replies',
  getParentRoute: () => ApiCommentsIdRoute,
} as any)
const ApiCommentsIdShareRoute = ApiCommentsIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ApiCommentsIdRoute,
} as any)
const ApiEventsIdActivityRoute = ApiEventsIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ApiEventsIdRoute,
} as any)
const ApiEventsIdHoldersRoute = ApiEventsIdHoldersRouteImport.update({
  id: '/holders',
  path: '/holders',
  getParentRoute: () => ApiEventsIdRoute,
} as any)
const ApiMarketsIdActivityRoute = ApiMarketsIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ApiMarketsIdRoute,
} as any)
const ApiMarketsIdHoldersRoute = ApiMarketsIdHoldersRouteImport.update({
  id: '/holders',
  path: '/holders',
  getParentRoute: () => ApiMarketsIdRoute,
} as any)
const ApiMarketsIdPriceHistoryRoute =
  ApiMarketsIdPriceHistoryRouteImport.update({
    id: '/price-history',
    path: '/price-history',
    getParentRoute: () => ApiMarketsIdRoute,
  } as any)
const ApiMarketsIdTradeEstimateRoute =
  ApiMarketsIdTradeEstimateRouteImport.update({
    id: '/trade-estimate',
    path: '/trade-estimate',
    getParentRoute: () => ApiMarketsIdRoute,
  } as any)
const ApiUsersIdActivityRoute = ApiUsersIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ApiUsersIdRoute,
} as any)
const ApiUsersIdCallsRoute = ApiUsersIdCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => ApiUsersIdRoute,
} as any)
const ApiUsersIdFollowRoute = ApiUsersIdFollowRouteImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => ApiUsersIdRoute,
} as any)
const ApiUsersIdFollowersRoute = ApiUsersIdFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => ApiUsersIdRoute,
} as any)
const ApiUsersIdFollowingRoute = ApiUsersIdFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => ApiUsersIdRoute,
} as any)
const ApiUsersIdRepliesRoute = ApiUsersIdRepliesRouteImport.update({
  id: '/replies',
  path: '/replies',
  getParentRoute: () => ApiUsersIdRoute,
} as any)
const ApiUsersMeImagesRoute = ApiUsersMeImagesRouteImport.update({
  id: '/api/users/me/images',
  path: '/api/users/me/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletAllowanceRefreshRoute =
  ApiWalletAllowanceRefreshRouteImport.update({
    id: '/api/wallet/allowance/refresh',
    path: '/api/wallet/allowance/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/markets': typeof MarketsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/sign-in': typeof SignInRoute
  '/watchlist': typeof WatchlistRoute
  '/api/calls': typeof ApiCallsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/markets/': typeof MarketsIndexRoute
  '/api/calls/$id': typeof ApiCallsIdRouteWithChildren
  '/api/comments/$id': typeof ApiCommentsIdRouteWithChildren
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/feed/following': typeof ApiFeedFollowingRoute
  '/api/markets/$id': typeof ApiMarketsIdRouteWithChildren
  '/api/positions/$marketId': typeof ApiPositionsMarketIdRoute
  '/api/trading/orders': typeof ApiTradingOrdersRoute
  '/api/trading/sell': typeof ApiTradingSellRoute
  '/api/users/$id': typeof ApiUsersIdRouteWithChildren
  '/api/users/suggestions': typeof ApiUsersSuggestionsRoute
  '/api/wallet/balance': typeof ApiWalletBalanceRoute
  '/api/wallet/deposit-wallet': typeof ApiWalletDepositWalletRoute
  '/api/calls/$id/comments': typeof ApiCallsIdCommentsRoute
  '/api/calls/$id/like': typeof ApiCallsIdLikeRoute
  '/api/comments/$id/like': typeof ApiCommentsIdLikeRoute
  '/api/comments/$id/replies': typeof ApiCommentsIdRepliesRoute
  '/api/comments/$id/share': typeof ApiCommentsIdShareRoute
  '/api/events/$id/activity': typeof ApiEventsIdActivityRoute
  '/api/events/$id/holders': typeof ApiEventsIdHoldersRoute
  '/api/markets/$id/activity': typeof ApiMarketsIdActivityRoute
  '/api/markets/$id/holders': typeof ApiMarketsIdHoldersRoute
  '/api/markets/$id/price-history': typeof ApiMarketsIdPriceHistoryRoute
  '/api/markets/$id/trade-estimate': typeof ApiMarketsIdTradeEstimateRoute
  '/api/users/$id/activity': typeof ApiUsersIdActivityRoute
  '/api/users/$id/calls': typeof ApiUsersIdCallsRoute
  '/api/users/$id/follow': typeof ApiUsersIdFollowRoute
  '/api/users/$id/followers': typeof ApiUsersIdFollowersRoute
  '/api/users/$id/following': typeof ApiUsersIdFollowingRoute
  '/api/users/$id/replies': typeof ApiUsersIdRepliesRoute
  '/api/users/me/images': typeof ApiUsersMeImagesRoute
  '/api/wallet/allowance/refresh': typeof ApiWalletAllowanceRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/portfolio': typeof PortfolioRoute
  '/sign-in': typeof SignInRoute
  '/watchlist': typeof WatchlistRoute
  '/api/calls': typeof ApiCallsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/markets': typeof MarketsIndexRoute
  '/api/calls/$id': typeof ApiCallsIdRouteWithChildren
  '/api/comments/$id': typeof ApiCommentsIdRouteWithChildren
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/feed/following': typeof ApiFeedFollowingRoute
  '/api/markets/$id': typeof ApiMarketsIdRouteWithChildren
  '/api/positions/$marketId': typeof ApiPositionsMarketIdRoute
  '/api/trading/orders': typeof ApiTradingOrdersRoute
  '/api/trading/sell': typeof ApiTradingSellRoute
  '/api/users/$id': typeof ApiUsersIdRouteWithChildren
  '/api/users/suggestions': typeof ApiUsersSuggestionsRoute
  '/api/wallet/balance': typeof ApiWalletBalanceRoute
  '/api/wallet/deposit-wallet': typeof ApiWalletDepositWalletRoute
  '/api/calls/$id/comments': typeof ApiCallsIdCommentsRoute
  '/api/calls/$id/like': typeof ApiCallsIdLikeRoute
  '/api/comments/$id/like': typeof ApiCommentsIdLikeRoute
  '/api/comments/$id/replies': typeof ApiCommentsIdRepliesRoute
  '/api/comments/$id/share': typeof ApiCommentsIdShareRoute
  '/api/events/$id/activity': typeof ApiEventsIdActivityRoute
  '/api/events/$id/holders': typeof ApiEventsIdHoldersRoute
  '/api/markets/$id/activity': typeof ApiMarketsIdActivityRoute
  '/api/markets/$id/holders': typeof ApiMarketsIdHoldersRoute
  '/api/markets/$id/price-history': typeof ApiMarketsIdPriceHistoryRoute
  '/api/markets/$id/trade-estimate': typeof ApiMarketsIdTradeEstimateRoute
  '/api/users/$id/activity': typeof ApiUsersIdActivityRoute
  '/api/users/$id/calls': typeof ApiUsersIdCallsRoute
  '/api/users/$id/follow': typeof ApiUsersIdFollowRoute
  '/api/users/$id/followers': typeof ApiUsersIdFollowersRoute
  '/api/users/$id/following': typeof ApiUsersIdFollowingRoute
  '/api/users/$id/replies': typeof ApiUsersIdRepliesRoute
  '/api/users/me/images': typeof ApiUsersMeImagesRoute
  '/api/wallet/allowance/refresh': typeof ApiWalletAllowanceRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/markets': typeof MarketsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/sign-in': typeof SignInRoute
  '/watchlist': typeof WatchlistRoute
  '/api/calls': typeof ApiCallsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/positions': typeof ApiPositionsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/markets/': typeof MarketsIndexRoute
  '/api/calls/$id': typeof ApiCallsIdRouteWithChildren
  '/api/comments/$id': typeof ApiCommentsIdRouteWithChildren
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/feed/following': typeof ApiFeedFollowingRoute
  '/api/markets/$id': typeof ApiMarketsIdRouteWithChildren
  '/api/positions/$marketId': typeof ApiPositionsMarketIdRoute
  '/api/trading/orders': typeof ApiTradingOrdersRoute
  '/api/trading/sell': typeof ApiTradingSellRoute
  '/api/users/$id': typeof ApiUsersIdRouteWithChildren
  '/api/users/suggestions': typeof ApiUsersSuggestionsRoute
  '/api/wallet/balance': typeof ApiWalletBalanceRoute
  '/api/wallet/deposit-wallet': typeof ApiWalletDepositWalletRoute
  '/api/calls/$id/comments': typeof ApiCallsIdCommentsRoute
  '/api/calls/$id/like': typeof ApiCallsIdLikeRoute
  '/api/comments/$id/like': typeof ApiCommentsIdLikeRoute
  '/api/comments/$id/replies': typeof ApiCommentsIdRepliesRoute
  '/api/comments/$id/share': typeof ApiCommentsIdShareRoute
  '/api/events/$id/activity': typeof ApiEventsIdActivityRoute
  '/api/events/$id/holders': typeof ApiEventsIdHoldersRoute
  '/api/markets/$id/activity': typeof ApiMarketsIdActivityRoute
  '/api/markets/$id/holders': typeof ApiMarketsIdHoldersRoute
  '/api/markets/$id/price-history': typeof ApiMarketsIdPriceHistoryRoute
  '/api/markets/$id/trade-estimate': typeof ApiMarketsIdTradeEstimateRoute
  '/api/users/$id/activity': typeof ApiUsersIdActivityRoute
  '/api/users/$id/calls': typeof ApiUsersIdCallsRoute
  '/api/users/$id/follow': typeof ApiUsersIdFollowRoute
  '/api/users/$id/followers': typeof ApiUsersIdFollowersRoute
  '/api/users/$id/following': typeof ApiUsersIdFollowingRoute
  '/api/users/$id/replies': typeof ApiUsersIdRepliesRoute
  '/api/users/me/images': typeof ApiUsersMeImagesRoute
  '/api/wallet/allowance/refresh': typeof ApiWalletAllowanceRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/markets'
    | '/portfolio'
    | '/sign-in'
    | '/watchlist'
    | '/api/calls'
    | '/api/categories'
    | '/api/events'
    | '/api/feed'
    | '/api/leaderboard'
    | '/api/markets'
    | '/api/positions'
    | '/api/search'
    | '/markets/$marketId'
    | '/markets/'
    | '/api/calls/$id'
    | '/api/comments/$id'
    | '/api/events/$id'
    | '/api/feed/following'
    | '/api/markets/$id'
    | '/api/positions/$marketId'
    | '/api/trading/orders'
    | '/api/trading/sell'
    | '/api/users/$id'
    | '/api/users/suggestions'
    | '/api/wallet/balance'
    | '/api/wallet/deposit-wallet'
    | '/api/calls/$id/comments'
    | '/api/calls/$id/like'
    | '/api/comments/$id/like'
    | '/api/comments/$id/replies'
    | '/api/comments/$id/share'
    | '/api/events/$id/activity'
    | '/api/events/$id/holders'
    | '/api/markets/$id/activity'
    | '/api/markets/$id/holders'
    | '/api/markets/$id/price-history'
    | '/api/markets/$id/trade-estimate'
    | '/api/users/$id/activity'
    | '/api/users/$id/calls'
    | '/api/users/$id/follow'
    | '/api/users/$id/followers'
    | '/api/users/$id/following'
    | '/api/users/$id/replies'
    | '/api/users/me/images'
    | '/api/wallet/allowance/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/portfolio'
    | '/sign-in'
    | '/watchlist'
    | '/api/calls'
    | '/api/categories'
    | '/api/events'
    | '/api/feed'
    | '/api/leaderboard'
    | '/api/markets'
    | '/api/positions'
    | '/api/search'
    | '/markets/$marketId'
    | '/markets'
    | '/api/calls/$id'
    | '/api/comments/$id'
    | '/api/events/$id'
    | '/api/feed/following'
    | '/api/markets/$id'
    | '/api/positions/$marketId'
    | '/api/trading/orders'
    | '/api/trading/sell'
    | '/api/users/$id'
    | '/api/users/suggestions'
    | '/api/wallet/balance'
    | '/api/wallet/deposit-wallet'
    | '/api/calls/$id/comments'
    | '/api/calls/$id/like'
    | '/api/comments/$id/like'
    | '/api/comments/$id/replies'
    | '/api/comments/$id/share'
    | '/api/events/$id/activity'
    | '/api/events/$id/holders'
    | '/api/markets/$id/activity'
    | '/api/markets/$id/holders'
    | '/api/markets/$id/price-history'
    | '/api/markets/$id/trade-estimate'
    | '/api/users/$id/activity'
    | '/api/users/$id/calls'
    | '/api/users/$id/follow'
    | '/api/users/$id/followers'
    | '/api/users/$id/following'
    | '/api/users/$id/replies'
    | '/api/users/me/images'
    | '/api/wallet/allowance/refresh'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/markets'
    | '/portfolio'
    | '/sign-in'
    | '/watchlist'
    | '/api/calls'
    | '/api/categories'
    | '/api/events'
    | '/api/feed'
    | '/api/leaderboard'
    | '/api/markets'
    | '/api/positions'
    | '/api/search'
    | '/markets/$marketId'
    | '/markets/'
    | '/api/calls/$id'
    | '/api/comments/$id'
    | '/api/events/$id'
    | '/api/feed/following'
    | '/api/markets/$id'
    | '/api/positions/$marketId'
    | '/api/trading/orders'
    | '/api/trading/sell'
    | '/api/users/$id'
    | '/api/users/suggestions'
    | '/api/wallet/balance'
    | '/api/wallet/deposit-wallet'
    | '/api/calls/$id/comments'
    | '/api/calls/$id/like'
    | '/api/comments/$id/like'
    | '/api/comments/$id/replies'
    | '/api/comments/$id/share'
    | '/api/events/$id/activity'
    | '/api/events/$id/holders'
    | '/api/markets/$id/activity'
    | '/api/markets/$id/holders'
    | '/api/markets/$id/price-history'
    | '/api/markets/$id/trade-estimate'
    | '/api/users/$id/activity'
    | '/api/users/$id/calls'
    | '/api/users/$id/follow'
    | '/api/users/$id/followers'
    | '/api/users/$id/following'
    | '/api/users/$id/replies'
    | '/api/users/me/images'
    | '/api/wallet/allowance/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  SignInRoute: typeof SignInRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiCallsRoute: typeof ApiCallsRouteWithChildren
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiEventsRoute: typeof ApiEventsRouteWithChildren
  ApiFeedRoute: typeof ApiFeedRouteWithChildren
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiMarketsRoute: typeof ApiMarketsRouteWithChildren
  ApiPositionsRoute: typeof ApiPositionsRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ApiCommentsIdRoute: typeof ApiCommentsIdRouteWithChildren
  ApiTradingOrdersRoute: typeof ApiTradingOrdersRoute
  ApiTradingSellRoute: typeof ApiTradingSellRoute
  ApiUsersIdRoute: typeof ApiUsersIdRouteWithChildren
  ApiUsersSuggestionsRoute: typeof ApiUsersSuggestionsRoute
  ApiWalletBalanceRoute: typeof ApiWalletBalanceRoute
  ApiWalletDepositWalletRoute: typeof ApiWalletDepositWalletRoute
  ApiUsersMeImagesRoute: typeof ApiUsersMeImagesRoute
  ApiWalletAllowanceRefreshRoute: typeof ApiWalletAllowanceRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls': {
      id: '/api/calls'
      path: '/api/calls'
      fullPath: '/api/calls'
      preLoaderRoute: typeof ApiCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/positions': {
      id: '/api/positions'
      path: '/api/positions'
      fullPath: '/api/positions'
      preLoaderRoute: typeof ApiPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/api/calls/$id': {
      id: '/api/calls/$id'
      path: '/$id'
      fullPath: '/api/calls/$id'
      preLoaderRoute: typeof ApiCallsIdRouteImport
      parentRoute: typeof ApiCallsRoute
    }
    '/api/comments/$id': {
      id: '/api/comments/$id'
      path: '/api/comments/$id'
      fullPath: '/api/comments/$id'
      preLoaderRoute: typeof ApiCommentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$id': {
      id: '/api/events/$id'
      path: '/$id'
      fullPath: '/api/events/$id'
      preLoaderRoute: typeof ApiEventsIdRouteImport
      parentRoute: typeof ApiEventsRoute
    }
    '/api/feed/following': {
      id: '/api/feed/following'
      path: '/following'
      fullPath: '/api/feed/following'
      preLoaderRoute: typeof ApiFeedFollowingRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/markets/$id': {
      id: '/api/markets/$id'
      path: '/$id'
      fullPath: '/api/markets/$id'
      preLoaderRoute: typeof ApiMarketsIdRouteImport
      parentRoute: typeof ApiMarketsRoute
    }
    '/api/positions/$marketId': {
      id: '/api/positions/$marketId'
      path: '/$marketId'
      fullPath: '/api/positions/$marketId'
      preLoaderRoute: typeof ApiPositionsMarketIdRouteImport
      parentRoute: typeof ApiPositionsRoute
    }
    '/api/trading/orders': {
      id: '/api/trading/orders'
      path: '/api/trading/orders'
      fullPath: '/api/trading/orders'
      preLoaderRoute: typeof ApiTradingOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trading/sell': {
      id: '/api/trading/sell'
      path: '/api/trading/sell'
      fullPath: '/api/trading/sell'
      preLoaderRoute: typeof ApiTradingSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/api/users/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/suggestions': {
      id: '/api/users/suggestions'
      path: '/api/users/suggestions'
      fullPath: '/api/users/suggestions'
      preLoaderRoute: typeof ApiUsersSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/balance': {
      id: '/api/wallet/balance'
      path: '/api/wallet/balance'
      fullPath: '/api/wallet/balance'
      preLoaderRoute: typeof ApiWalletBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/deposit-wallet': {
      id: '/api/wallet/deposit-wallet'
      path: '/api/wallet/deposit-wallet'
      fullPath: '/api/wallet/deposit-wallet'
      preLoaderRoute: typeof ApiWalletDepositWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/$id/comments': {
      id: '/api/calls/$id/comments'
      path: '/comments'
      fullPath: '/api/calls/$id/comments'
      preLoaderRoute: typeof ApiCallsIdCommentsRouteImport
      parentRoute: typeof ApiCallsIdRoute
    }
    '/api/calls/$id/like': {
      id: '/api/calls/$id/like'
      path: '/like'
      fullPath: '/api/calls/$id/like'
      preLoaderRoute: typeof ApiCallsIdLikeRouteImport
      parentRoute: typeof ApiCallsIdRoute
    }
    '/api/comments/$id/like': {
      id: '/api/comments/$id/like'
      path: '/like'
      fullPath: '/api/comments/$id/like'
      preLoaderRoute: typeof ApiCommentsIdLikeRouteImport
      parentRoute: typeof ApiCommentsIdRoute
    }
    '/api/comments/$id/replies': {
      id: '/api/comments/$id/replies'
      path: '/replies'
      fullPath: '/api/comments/$id/replies'
      preLoaderRoute: typeof ApiCommentsIdRepliesRouteImport
      parentRoute: typeof ApiCommentsIdRoute
    }
    '/api/comments/$id/share': {
      id: '/api/comments/$id/share'
      path: '/share'
      fullPath: '/api/comments/$id/share'
      preLoaderRoute: typeof ApiCommentsIdShareRouteImport
      parentRoute: typeof ApiCommentsIdRoute
    }
    '/api/events/$id/activity': {
      id: '/api/events/$id/activity'
      path: '/activity'
      fullPath: '/api/events/$id/activity'
      preLoaderRoute: typeof ApiEventsIdActivityRouteImport
      parentRoute: typeof ApiEventsIdRoute
    }
    '/api/events/$id/holders': {
      id: '/api/events/$id/holders'
      path: '/holders'
      fullPath: '/api/events/$id/holders'
      preLoaderRoute: typeof ApiEventsIdHoldersRouteImport
      parentRoute: typeof ApiEventsIdRoute
    }
    '/api/markets/$id/activity': {
      id: '/api/markets/$id/activity'
      path: '/activity'
      fullPath: '/api/markets/$id/activity'
      preLoaderRoute: typeof ApiMarketsIdActivityRouteImport
      parentRoute: typeof ApiMarketsIdRoute
    }
    '/api/markets/$id/holders': {
      id: '/api/markets/$id/holders'
      path: '/holders'
      fullPath: '/api/markets/$id/holders'
      preLoaderRoute: typeof ApiMarketsIdHoldersRouteImport
      parentRoute: typeof ApiMarketsIdRoute
    }
    '/api/markets/$id/price-history': {
      id: '/api/markets/$id/price-history'
      path: '/price-history'
      fullPath: '/api/markets/$id/price-history'
      preLoaderRoute: typeof ApiMarketsIdPriceHistoryRouteImport
      parentRoute: typeof ApiMarketsIdRoute
    }
    '/api/markets/$id/trade-estimate': {
      id: '/api/markets/$id/trade-estimate'
      path: '/trade-estimate'
      fullPath: '/api/markets/$id/trade-estimate'
      preLoaderRoute: typeof ApiMarketsIdTradeEstimateRouteImport
      parentRoute: typeof ApiMarketsIdRoute
    }
    '/api/users/$id/activity': {
      id: '/api/users/$id/activity'
      path: '/activity'
      fullPath: '/api/users/$id/activity'
      preLoaderRoute: typeof ApiUsersIdActivityRouteImport
      parentRoute: typeof ApiUsersIdRoute
    }
    '/api/users/$id/calls': {
      id: '/api/users/$id/calls'
      path: '/calls'
      fullPath: '/api/users/$id/calls'
      preLoaderRoute: typeof ApiUsersIdCallsRouteImport
      parentRoute: typeof ApiUsersIdRoute
    }
    '/api/users/$id/follow': {
      id: '/api/users/$id/follow'
      path: '/follow'
      fullPath: '/api/users/$id/follow'
      preLoaderRoute: typeof ApiUsersIdFollowRouteImport
      parentRoute: typeof ApiUsersIdRoute
    }
    '/api/users/$id/followers': {
      id: '/api/users/$id/followers'
      path: '/followers'
      fullPath: '/api/users/$id/followers'
      preLoaderRoute: typeof ApiUsersIdFollowersRouteImport
      parentRoute: typeof ApiUsersIdRoute
    }
    '/api/users/$id/following': {
      id: '/api/users/$id/following'
      path: '/following'
      fullPath: '/api/users/$id/following'
      preLoaderRoute: typeof ApiUsersIdFollowingRouteImport
      parentRoute: typeof ApiUsersIdRoute
    }
    '/api/users/$id/replies': {
      id: '/api/users/$id/replies'
      path: '/replies'
      fullPath: '/api/users/$id/replies'
      preLoaderRoute: typeof ApiUsersIdRepliesRouteImport
      parentRoute: typeof ApiUsersIdRoute
    }
    '/api/users/me/images': {
      id: '/api/users/me/images'
      path: '/api/users/me/images'
      fullPath: '/api/users/me/images'
      preLoaderRoute: typeof ApiUsersMeImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/allowance/refresh': {
      id: '/api/wallet/allowance/refresh'
      path: '/api/wallet/allowance/refresh'
      fullPath: '/api/wallet/allowance/refresh'
      preLoaderRoute: typeof ApiWalletAllowanceRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketsRouteChildren {
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsMarketIdRoute: MarketsMarketIdRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

interface ApiCallsIdRouteChildren {
  ApiCallsIdCommentsRoute: typeof ApiCallsIdCommentsRoute
  ApiCallsIdLikeRoute: typeof ApiCallsIdLikeRoute
}

const ApiCallsIdRouteChildren: ApiCallsIdRouteChildren = {
  ApiCallsIdCommentsRoute: ApiCallsIdCommentsRoute,
  ApiCallsIdLikeRoute: ApiCallsIdLikeRoute,
}

const ApiCallsIdRouteWithChildren = ApiCallsIdRoute._addFileChildren(
  ApiCallsIdRouteChildren,
)

interface ApiCallsRouteChildren {
  ApiCallsIdRoute: typeof ApiCallsIdRouteWithChildren
}

const ApiCallsRouteChildren: ApiCallsRouteChildren = {
  ApiCallsIdRoute: ApiCallsIdRouteWithChildren,
}

const ApiCallsRouteWithChildren = ApiCallsRoute._addFileChildren(
  ApiCallsRouteChildren,
)

interface ApiEventsIdRouteChildren {
  ApiEventsIdActivityRoute: typeof ApiEventsIdActivityRoute
  ApiEventsIdHoldersRoute: typeof ApiEventsIdHoldersRoute
}

const ApiEventsIdRouteChildren: ApiEventsIdRouteChildren = {
  ApiEventsIdActivityRoute: ApiEventsIdActivityRoute,
  ApiEventsIdHoldersRoute: ApiEventsIdHoldersRoute,
}

const ApiEventsIdRouteWithChildren = ApiEventsIdRoute._addFileChildren(
  ApiEventsIdRouteChildren,
)

interface ApiEventsRouteChildren {
  ApiEventsIdRoute: typeof ApiEventsIdRouteWithChildren
}

const ApiEventsRouteChildren: ApiEventsRouteChildren = {
  ApiEventsIdRoute: ApiEventsIdRouteWithChildren,
}

const ApiEventsRouteWithChildren = ApiEventsRoute._addFileChildren(
  ApiEventsRouteChildren,
)

interface ApiFeedRouteChildren {
  ApiFeedFollowingRoute: typeof ApiFeedFollowingRoute
}

const ApiFeedRouteChildren: ApiFeedRouteChildren = {
  ApiFeedFollowingRoute: ApiFeedFollowingRoute,
}

const ApiFeedRouteWithChildren =
  ApiFeedRoute._addFileChildren(ApiFeedRouteChildren)

interface ApiMarketsIdRouteChildren {
  ApiMarketsIdActivityRoute: typeof ApiMarketsIdActivityRoute
  ApiMarketsIdHoldersRoute: typeof ApiMarketsIdHoldersRoute
  ApiMarketsIdPriceHistoryRoute: typeof ApiMarketsIdPriceHistoryRoute
  ApiMarketsIdTradeEstimateRoute: typeof ApiMarketsIdTradeEstimateRoute
}

const ApiMarketsIdRouteChildren: ApiMarketsIdRouteChildren = {
  ApiMarketsIdActivityRoute: ApiMarketsIdActivityRoute,
  ApiMarketsIdHoldersRoute: ApiMarketsIdHoldersRoute,
  ApiMarketsIdPriceHistoryRoute: ApiMarketsIdPriceHistoryRoute,
  ApiMarketsIdTradeEstimateRoute: ApiMarketsIdTradeEstimateRoute,
}

const ApiMarketsIdRouteWithChildren = ApiMarketsIdRoute._addFileChildren(
  ApiMarketsIdRouteChildren,
)

interface ApiMarketsRouteChildren {
  ApiMarketsIdRoute: typeof ApiMarketsIdRouteWithChildren
}

const ApiMarketsRouteChildren: ApiMarketsRouteChildren = {
  ApiMarketsIdRoute: ApiMarketsIdRouteWithChildren,
}

const ApiMarketsRouteWithChildren = ApiMarketsRoute._addFileChildren(
  ApiMarketsRouteChildren,
)

interface ApiPositionsRouteChildren {
  ApiPositionsMarketIdRoute: typeof ApiPositionsMarketIdRoute
}

const ApiPositionsRouteChildren: ApiPositionsRouteChildren = {
  ApiPositionsMarketIdRoute: ApiPositionsMarketIdRoute,
}

const ApiPositionsRouteWithChildren = ApiPositionsRoute._addFileChildren(
  ApiPositionsRouteChildren,
)

interface ApiCommentsIdRouteChildren {
  ApiCommentsIdLikeRoute: typeof ApiCommentsIdLikeRoute
  ApiCommentsIdRepliesRoute: typeof ApiCommentsIdRepliesRoute
  ApiCommentsIdShareRoute: typeof ApiCommentsIdShareRoute
}

const ApiCommentsIdRouteChildren: ApiCommentsIdRouteChildren = {
  ApiCommentsIdLikeRoute: ApiCommentsIdLikeRoute,
  ApiCommentsIdRepliesRoute: ApiCommentsIdRepliesRoute,
  ApiCommentsIdShareRoute: ApiCommentsIdShareRoute,
}

const ApiCommentsIdRouteWithChildren = ApiCommentsIdRoute._addFileChildren(
  ApiCommentsIdRouteChildren,
)

interface ApiUsersIdRouteChildren {
  ApiUsersIdActivityRoute: typeof ApiUsersIdActivityRoute
  ApiUsersIdCallsRoute: typeof ApiUsersIdCallsRoute
  ApiUsersIdFollowRoute: typeof ApiUsersIdFollowRoute
  ApiUsersIdFollowersRoute: typeof ApiUsersIdFollowersRoute
  ApiUsersIdFollowingRoute: typeof ApiUsersIdFollowingRoute
  ApiUsersIdRepliesRoute: typeof ApiUsersIdRepliesRoute
}

const ApiUsersIdRouteChildren: ApiUsersIdRouteChildren = {
  ApiUsersIdActivityRoute: ApiUsersIdActivityRoute,
  ApiUsersIdCallsRoute: ApiUsersIdCallsRoute,
  ApiUsersIdFollowRoute: ApiUsersIdFollowRoute,
  ApiUsersIdFollowersRoute: ApiUsersIdFollowersRoute,
  ApiUsersIdFollowingRoute: ApiUsersIdFollowingRoute,
  ApiUsersIdRepliesRoute: ApiUsersIdRepliesRoute,
}

const ApiUsersIdRouteWithChildren = ApiUsersIdRoute._addFileChildren(
  ApiUsersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  MarketsRoute: MarketsRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  SignInRoute: SignInRoute,
  WatchlistRoute: WatchlistRoute,
  ApiCallsRoute: ApiCallsRouteWithChildren,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiEventsRoute: ApiEventsRouteWithChildren,
  ApiFeedRoute: ApiFeedRouteWithChildren,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiMarketsRoute: ApiMarketsRouteWithChildren,
  ApiPositionsRoute: ApiPositionsRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ApiCommentsIdRoute: ApiCommentsIdRouteWithChildren,
  ApiTradingOrdersRoute: ApiTradingOrdersRoute,
  ApiTradingSellRoute: ApiTradingSellRoute,
  ApiUsersIdRoute: ApiUsersIdRouteWithChildren,
  ApiUsersSuggestionsRoute: ApiUsersSuggestionsRoute,
  ApiWalletBalanceRoute: ApiWalletBalanceRoute,
  ApiWalletDepositWalletRoute: ApiWalletDepositWalletRoute,
  ApiUsersMeImagesRoute: ApiUsersMeImagesRoute,
  ApiWalletAllowanceRefreshRoute: ApiWalletAllowanceRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
