import type { Metadata } from 'next';
import { LegalPage, LegalSection } from '@/components/LegalPage';

export const metadata: Metadata = { title: 'Privacy Policy · Knewit' };

const List = ({ children }: { children: React.ReactNode }) => <ul className="list-disc space-y-1 pl-5">{children}</ul>;

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" effectiveDate="September 21, 2026">
    <p>This Privacy Policy explains how Knewit (“Knewit,” “we,” “us,” or “our”) collects, uses, stores, and shares information when you access or use the Knewit mobile application, website, and related services (collectively, the “Services”).</p>
    <p>Knewit is a social prediction market platform that may integrate third-party services, including Polymarket for prediction market information and functionality and Privy for authentication and embedded wallet functionality.</p>
    <p>By accessing or using Knewit, you acknowledge that you have read and understood this Privacy Policy.</p>
    <LegalSection title="1. Information We Collect"><p>The information we collect depends on how you interact with Knewit and which features you use.</p><h3 className="mt-5 font-semibold text-landing-ink">Information You Provide</h3><p>We may collect information you voluntarily provide when creating an account, completing your profile, interacting with users, contacting us, or using the Services.</p><List><li>Name or display name</li><li>Email address</li><li>Username</li><li>Profile picture</li><li>Social media account information</li><li>Profile and account preferences</li><li>Posts, callouts, comments, replies, and other user-generated content</li><li>Information provided when contacting support</li></List><h3 className="mt-5 font-semibold text-landing-ink">Authentication Information</h3><p>Knewit uses Privy for authentication. Depending on your authentication method, Privy or an authentication provider may provide your email address, name, profile picture, social account identifier, authentication identifier, and other information authorized by you. Your use of Privy is also subject to Privy’s own terms and privacy practices.</p><h3 className="mt-5 font-semibold text-landing-ink">Wallet Information</h3><p>Knewit may use Privy to provide or connect cryptocurrency wallets. We may process your public wallet address, wallet type, blockchain network, public transactions, transaction identifiers, public balances or asset information, and information associating a wallet with your account.</p><p>Blockchain transactions may be public and permanent. Knewit does not intentionally request private keys or seed phrases. Never provide a seed phrase or private key to Knewit support personnel or other users.</p><h3 className="mt-5 font-semibold text-landing-ink">Polymarket Information</h3><p>Knewit may integrate with Polymarket to display market titles, descriptions, outcomes, YES/NO prices, probabilities, volume, liquidity, categories, status, public trading information, and supported wallet position or transaction information.</p><p>Interactions with Polymarket may be subject to Polymarket’s terms, policies, eligibility requirements, geographic restrictions, and regulatory requirements. Knewit does not control Polymarket’s services or policies.</p></LegalSection>
    <LegalSection title="2. Automatically Collected Information"><p>We may automatically collect IP address, device type, operating system, browser type, application version, device identifiers, language settings, general geographic information, pages or screens viewed, features used, interaction events, crash and diagnostic information, and date and time of access.</p><p>We use this information for security, analytics, troubleshooting, fraud prevention, and improvement of the Services.</p></LegalSection>
    <LegalSection title="3. Social Features and User-Generated Content"><p>Knewit may allow users to create and interact with prediction-market callouts, posts, comments, replies, likes, follows, profiles, trading or prediction-related activity, and public wallet-related information.</p><p>Information you publish may be visible to other users. Avoid publishing confidential, sensitive, or personally identifying information in public areas.</p></LegalSection>
    <LegalSection title="4. How We Use Your Information"><p>We may process information to:</p><List><li>Create and manage your account</li><li>Authenticate users</li><li>Provide wallet functionality</li><li>Display prediction markets and market information</li><li>Provide Polymarket-related and social functionality</li><li>Associate content with users</li><li>Display public wallet activity where applicable</li><li>Maintain security and detect fraud, abuse, or unauthorized activity</li><li>Diagnose technical problems and improve performance</li><li>Understand use of Knewit</li><li>Communicate service or policy updates</li><li>Provide customer support</li><li>Comply with legal obligations</li></List></LegalSection>
    <LegalSection title="5. Privy"><p>Knewit uses Privy as a third-party infrastructure provider for authentication and wallet functionality. Privy may process information necessary for user authentication, email or social login, account identifiers, embedded-wallet creation, wallet authentication, and wallet signing functionality.</p><p>Information processed by Privy may be governed by Privy’s own privacy policy and terms. Knewit does not control how Privy independently processes information under its own services.</p></LegalSection>
    <LegalSection title="6. Polymarket"><p>Knewit may use Polymarket APIs and related infrastructure to retrieve prediction market information and, where supported, facilitate interactions with prediction markets.</p><p>Polymarket may independently collect or process information when you interact with its infrastructure under its own privacy policy, terms, eligibility requirements, and other policies.</p><p>Availability may vary based on your location, regulations, Polymarket eligibility, wallet compatibility, technical availability, and third-party restrictions. Knewit does not guarantee every Polymarket feature will be available to every user.</p></LegalSection>
    <LegalSection title="7. Blockchain Information"><p>Blockchain networks are generally public. Blockchain activity may create permanent records containing wallet addresses, transaction hashes, amounts, smart-contract interactions, token transfers, and timestamps. Knewit cannot delete or modify information already recorded on a public blockchain.</p></LegalSection>
    <LegalSection title="8. How We Share Information"><p>We may share information with providers needed to operate Knewit, including authentication, wallet infrastructure, prediction-market infrastructure, database, hosting, cloud, analytics, security, and error-monitoring providers. Examples may include Privy and Polymarket.</p><p>We may also disclose information when required by law, regulation, legal process, or governmental request, or when reasonably necessary to protect Knewit, users, or others from fraud, abuse, security threats, or illegal activity.</p></LegalSection>
    <LegalSection title="9. Third-Party Services"><p>Knewit may integrate with or link to third-party websites, applications, blockchain networks, or services. They operate independently, and their processing is governed by their own policies and terms. Review the policies of services involving authentication, wallets, blockchains, or prediction markets.</p></LegalSection>
    <LegalSection title="10. Data Security"><p>We use reasonable technical and organizational measures intended to protect information. However, no internet service, database, wallet system, blockchain network, or transmission method can be guaranteed completely secure.</p><p>You are responsible for securing your devices, accounts, authentication methods, and wallet credentials. Never share your password, private key, recovery phrase, or seed phrase.</p></LegalSection>
    <LegalSection title="11. Data Retention"><p>We may retain information as reasonably necessary to provide the Services, maintain accounts, fulfill this policy, prevent fraud and abuse, resolve disputes, maintain security, and meet legal or regulatory requirements. Retention varies by information type. Public blockchain information may remain permanently available and cannot be deleted by Knewit.</p></LegalSection>
    <LegalSection title="12. Account and Data Deletion"><p>Where supported, users may request deletion of their Knewit account and associated personal information. Information may be retained for legal, security, fraud-prevention, or compliance purposes.</p><p>Deleting an account does not delete public blockchain records. Information independently held by Privy or Polymarket is subject to their respective deletion policies.</p></LegalSection>
    <LegalSection title="13. Children’s Privacy"><p>Knewit is not intended for children. Users must meet applicable minimum-age requirements for Knewit and third-party services. Prediction-market or financial functionality may also have additional age, geographic, regulatory, or eligibility restrictions.</p></LegalSection>
    <LegalSection title="14. International Data Processing"><p>Knewit and its providers may process information in countries other than where you reside. Where required, appropriate safeguards may be implemented for international transfers.</p></LegalSection>
    <LegalSection title="15. Your Privacy Rights"><p>Depending on where you live, privacy laws may give you the right to request access, correction, deletion, restriction, objection, a copy of certain information, or withdrawal of consent where processing is based on consent. These rights may be subject to legal exceptions.</p></LegalSection>
    <LegalSection title="16. Changes to This Privacy Policy"><p>We may update this policy to reflect changes to Knewit’s features, technology, integrations, legal requirements, or business practices. For material changes, we may provide notice through the app, website, email, or another appropriate method. The date at the top indicates when it was last updated.</p></LegalSection>
    <LegalSection title="17. Contact Us"><p>If you have questions, concerns, or requests regarding this Privacy Policy or your personal information, contact Knewit through the official support contact provided in the application or on the Knewit website.</p></LegalSection>
  </LegalPage>;
}
